[GlobalParams]
  global_init_P = 1.1e5
  global_init_V = 0.5
  global_init_T = 628.15
  Tsolid_sf = 1e-1

  [./PBModelParams]
    pbm_scaling_factors = '1 1e-3 1e-6'
    passive_scalar = 'particle1  particle2  particle3'
    passive_scalar_diffusivity = '0.0  0.0  0.0'
    passive_scalar_decay_constant = '0.060  0.060  0.060'
    global_init_PS = '10.0  80.0  20.0'
    p_order = 2
    Courant_control = true
  [../]
[]

[EOS]
  [./eos]
    type = PBSodiumEquationOfState
  [../]
[]

[Functions]
  [./power_history]
    type = PiecewiseLinear
    x = '-1000.0	0.0		20.0	25.0	1000.0'
    y = '1.0		1.0		1.0		0.1		0.1'
  [../]

  [./TimeStepperFunc]
    type = PiecewiseLinear
    x = ' -300		-298	-297	-280	-279	-220	-219	0.0		1.0		19.0	20.0	25.0	26.0	35.0	36.0	50.0	51.0    1e5'
    y =' 0.1 		0.1   	0.2  	0.2   	0.5  	0.5    	1       1		0.5		0.5		0.1		0.1		0.2		0.2		0.5		0.5		1.0		1.0'
  [../]


[]

[Materials]
  [./ss-mat]
    type = SolidMaterialProps
    k = 20
    Cp = 638
    rho = 6e3
  [../]
[]

[Components]

  [./reactor]
    type = ReactorPower
    initial_power = 10e6
    decay_heat = power_history
  [../]

  [./pipe1]
    type = PBOneDFluidComponent
    eos = eos
    position = '0 1 0'
    orientation = '0 -1 0'

    A = 0.44934
    Dh = 2.972e-3
    length = 1
    n_elems = 10
    f = 0.001
  [../]

  [./CH1_MSR]
    type = PBMoltenSaltChannel
    eos = eos
    position = '0 0 0'
    orientation = '0 0 1'

    A = 0.44934
    Dh = 2.972e-3
    length = 0.8
    n_elems = 10

    f = 0.022 #Mcadms
    power_fraction = '1.0'

    ###################################################
    ### Define the delay neutron precursor generated by fission power
    ###################################################

    power_product_name = 'particle1  particle2  particle3'
    beta = '0.00125  0.01000  0.00250'   # Beta effective for delay neutron precursor
  [../]

  [./pipe2]
    type = PBOneDFluidComponent
    eos = eos
    position = '0 0 0.8'
    orientation = '0 0 1'

    A = 0.44934
    Dh = 2.972e-3
    length = 5.18
    n_elems = 10
    f = 0.001
  [../]

  [./pipe3]
    type = PBOneDFluidComponent
    eos = eos
    position = '0 0 5.98'
    orientation = '0 1 0'

    A = 0.44934
    Dh = 2.972e-3
    length = 1
    n_elems = 10
    f = 0.001
  [../]

  [./IHX]
    type = PBHeatExchanger
    eos = eos
    eos_secondary = eos

    position = '0 0.976 5.98'
    orientation = '0 0 -1'
    A = 0.44934
    Dh = 0.0186
    A_secondary = 0.44934
    Dh_secondary = 0.0186
    length = 0.8
    n_elems = 10
    f = 0.022

    initial_V_secondary = -0.2

    HT_surface_area_density = 1e3
    HT_surface_area_density_secondary = 1e3

    Twall_init = 628.15
    wall_thickness = 0.004

    dim_wall = 1
    material_wall = ss-mat
    n_wall_elems = 2
    scalar_source = '-2.0  -16.0  -4.0'
  [../]

  [./pipe4]
    type = PBOneDFluidComponent
    eos = eos
    position = '0 1.0 5.18'
    orientation = '0 0 -1'

    A = 0.44934
    Dh = 2.972e-3
    length = 5.18
    n_elems = 10
    f = 0.001
  [../]

  [./Branch1]
    type = PBBranch
    inputs = 'pipe1(out)'
    outputs = 'CH1_MSR(in) '
    eos = eos
    K = '0.0 0.0'
    Area = 0.44934
  [../]
  [./Branch2]
    type = PBBranch
    inputs = 'CH1_MSR(out) '
    outputs = 'pipe2(in)'
    K = '0.0 0.0'
    Area = 0.44934
    eos = eos
  [../]
  [./Branch3]
    type = PBBranch
    inputs = 'pipe2(out)'
    outputs = 'pipe3(in) pipe5(in)'
    K = '0.0 0.0 10.0'
    Area = 0.44934
    initial_P = 1e5
    eos = eos
  [../]
  [./Branch4]
    type = PBBranch
    inputs = 'pipe3(out)'
    outputs = 'IHX(primary_in)'
    K = '0.0 0.0'
    Area = 0.44934
    eos = eos
  [../]
  [./Branch5]
    type = PBBranch
    inputs = 'IHX(primary_out)'
    outputs = 'pipe4(in)'
    K = '0.0 0.0'
    Area = 0.44934
    eos = eos
  [../]

###### swith between Brach6 and Pump_p for natural circulation or forced flow

  [./Pump_p]
    type = PBPump                               # This is a PBPump component
    eos = eos
    inputs = 'pipe4(out)'
    outputs = 'pipe1(in)'
    K = '0. 0.'                                 # Form loss coefficient at pump inlet and outlet
    Area = 0.44934                              # Reference pump flow area
    initial_P = 1.5e5                           # Initial pressure
    Head = 1e3                                  # Pump head, Pa
  [../]

  [./pipe5]
    type = PBOneDFluidComponent
    eos = eos
    position = '0 0 5.98'
    orientation = '0 0 1'
    A = 0.44934
    Dh = 2.972e-3
    length = 0.1
    n_elems = 2
    f = 0.001
  [../]
  [./p_out]
    type = PBTDV
    input = 'pipe5(out)'
    eos = eos
    p_bc = '1e5'
    T_bc = 628.15
    S_bc = '10.0  80.0  20.0'
  [../]

  [./inlet2]
    type = PBTDJ
    input = 'IHX(secondary_in)'
    eos = eos
    v_bc = -1
    T_bc = 606.15
    S_bc = '10.0  80.0  20.0'
  [../]

  [./outlet2]
    type = PressureOutlet
    input = 'IHX(secondary_out)'
    eos = eos
    p_bc = 1.0e5
  [../]
[]

[Postprocessors]
  [./CH1_flow]                                      # Output mass flow rate at inlet of CH1
    type = ComponentBoundaryFlow
    input = CH1_MSR(in)
  [../]

  [./CH1_TP1_in]
    type = ComponentBoundaryVariableValue
    variable = particle1
    input = CH1_MSR(in)
  [../]
  [./CH1_TP1_flow_in]
    type = ComponentBoundaryScalarFlow
    variable = particle1
    input = CH1_MSR(in)
  [../]

  [./CH1_TP1_out]
    type = ComponentBoundaryVariableValue
    variable = particle1
    input = CH1_MSR(out)
  [../]
  [./CH1_TP1_flow_out]
    type = ComponentBoundaryScalarFlow
    variable = particle1
    input = CH1_MSR(out)
  [../]

  [./CH1_TP2_in]
    type = ComponentBoundaryVariableValue
    variable = particle2
    input = CH1_MSR(in)
  [../]
  [./CH1_TP2_flow_in]
    type = ComponentBoundaryScalarFlow
    variable = particle2
    input = CH1_MSR(in)
  [../]

  [./CH1_TP2_out]
    type = ComponentBoundaryVariableValue
    variable = particle2
    input = CH1_MSR(out)
  [../]
  [./CH1_TP2_flow_out]
    type = ComponentBoundaryScalarFlow
    variable = particle2
    input = CH1_MSR(out)
  [../]

  [./CH1_TP3_in]
    type = ComponentBoundaryVariableValue
    variable = particle3
    input = CH1_MSR(in)
  [../]
  [./CH1_TP3_flow_in]
    type = ComponentBoundaryScalarFlow
    variable = particle3
    input = CH1_MSR(in)
  [../]

  [./CH1_TP3_out]
    type = ComponentBoundaryVariableValue
    variable = particle3
    input = CH1_MSR(out)
  [../]
  [./CH1_TP3_flow_out]
    type = ComponentBoundaryScalarFlow
    variable = particle3
    input = CH1_MSR(out)
  [../]

  [./IHX_TP1_in]
    type = ComponentBoundaryVariableValue
    variable = particle1
    input = IHX(primary_in)
  [../]
  [./IHX_TP1_out]
    type = ComponentBoundaryVariableValue
    variable = particle1
    input = IHX(primary_out)
  [../]

  [./IHX_TP2_in]
    type = ComponentBoundaryVariableValue
    variable = particle2
    input = IHX(primary_in)
  [../]
  [./IHX_TP2_out]
    type = ComponentBoundaryVariableValue
    variable = particle2
    input = IHX(primary_out)
  [../]

  [./IHX_TP3_in]
    type = ComponentBoundaryVariableValue
    variable = particle3
    input = IHX(primary_in)
  [../]
  [./IHX_TP3_out]
    type = ComponentBoundaryVariableValue
    variable = particle3
    input = IHX(primary_out)
  [../]
[]

[Preconditioning]
  active = 'SMP_PJFNK'
  [./SMP_PJFNK]
    type = SMP
    full = true
    solve_type = 'PJFNK'
    petsc_options_iname = '-pc_type -ksp_gmres_restart'
    petsc_options_value = 'lu 101'
  [../]
[]

[Executioner]
  type = Transient

  [./TimeStepper]
    type = FunctionDT
    function = TimeStepperFunc
    min_dt = 1e-2
  [../]

  start_time = 0.0
  end_time = 200.0
  num_steps = 20000

  nl_rel_tol = 1e-8
  nl_abs_tol = 1e-7
  nl_max_its = 20
  l_tol = 1e-6
  l_max_its = 100

  [./Quadrature]
    type = GAUSS
    order = SECOND
  [../]
[]

#[Problem]
#    restart_file_base = loop_MSR_channel_DNP-SS_checkpoint_cp/0468
#[]


[Outputs]
  print_linear_residuals = false
  [./out_displaced]
    type = Exodus
    use_displaced = true
    execute_on = 'initial timestep_end'
    sequence = false
  [../]

# [./csv]
#   type = CSV
# []

  [./console]
    type = Console
    perf_log = true
  [../]

#   [./checkpoint]
#     type = Checkpoint
#     num_files = 1
#   [../]

[]
